# .github/workflows/build.yml

name: Build Plugin and Tester

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build the Plugin (CPUCoreBars.dll)
      run: msbuild CPUCoreBars/CPUCoreBars.vcxproj -p:Configuration=Release -p:Platform=x64

    - name: Build the Tester (Tester.exe)
      run: msbuild Tester/Tester.vcxproj -p:Configuration=Release -p:Platform=x64

    # 关键的调试步骤：
    # 在上传之前，递归地列出当前工作目录下的所有文件。
    # 这将明确地告诉我们 .dll 和 .exe 文件被生成在了哪里。
    - name: List all files in the workspace
      run: dir /s
      shell: cmd

    # 最终的上传步骤：
    # 我们现在提供一个更通配的路径来查找文件，无论它们被放在哪个子目录中。
    - name: Upload Artifacts (DLL and EXE)
      uses: actions/upload-artifact@v4
      with:
        name: plugin-and-tester
        path: |
          **/Release/*.dll
          **/Release/*.exe
