# .github/workflows/build.yml

name: Build CPUCoreBars Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    # 修正：在 msbuild 命令中添加 /clr 支持
    - name: Build the solution
      run: msbuild CPUCoreBars.sln -p:Configuration=Release -p:Platform=x64 -p:CLRSupport=true

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpu-core-bars-plugin-dll
        path: x64/Release/CPUCoreBars.dll
