# .github/workflows/build.yml

name: Build Plugin and Tester

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build the Plugin (CPUCoreBars.dll)
      run: msbuild CPUCoreBars/CPUCoreBars.vcxproj -p:Configuration=Release -p:Platform=x64

    - name: Build the Tester (Tester.exe)
      run: msbuild Tester/Tester.vcxproj -p:Configuration=Release -p:Platform=x64

    - name: Upload Artifacts (DLL and EXE)
      uses: actions/upload-artifact@v4
      with:
        name: plugin-and-tester
        path: |
          x64/Release/CPUCoreBars.dll
          x64/Release/Tester.exe
