# .github/workflows/build.yml

name: Build Plugin and Tester

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    # 移除了下载 NVML SDK 的步骤

    - name: Build the Plugin solution
      run: msbuild CPUCoreBars.sln -p:Configuration=Release -p:Platform=x64

    - name: Build the Tester application
      run: msbuild Tester/Tester.vcxproj -p:Configuration=Release -p:Platform=x64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugin-and-tester
        path: |
          x64/Release/CPUCoreBars.dll
          x64/Release/Tester.exe
